spring:
  application:
    name: TurboMechanics
  
  datasource: 
    url: jdbc:postgresql://localhost:5432/Turbo_Mechanics
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate: 
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: santimosquerav@gmail.com       # Cambiar por el correo del taller
    password: santiago0103           # Contraseña de aplicación de Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090

security:
  jwt:
    secret-key: QjaJfdfFv7krX863yrVAS87tfaz56rUWcrUzS0ZbqFU= # Genera con openssl rand -base64 32
    token-expiration: 600000 # 10 min expresado en ms
