spring:
  application:
    name: TurboMechanics
  
  datasource: 
    url: jdbc:postgresql://localhost:5432/Turbo_Mechanics
    username: postgres
    password: santi0103
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: TurboMechanicsTaller@gmail.com
    password: vvjl okct lprl bomr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090

security:
  jwt:
    secret-key: QjaJfdfFv7krX863yrVAS87tfaz56rUWcrUzS0ZbqFU= # Genera con openssl rand -base64 32
    token-expiration: 600000 # 10 min expresado en ms

whatsapp:
  service:
    url: http://localhost:3001
    token: turbo_mechanics_2026
  session:
    default: admin
    
app:
  frontend:
    url: http://localhost:4200

mercadopago:
  access-token: APP_USR-7726278336164374-060415-e160bbde422ec8723d23c5f42247a7b0-3450458282
  public-key: APP_USR-3fc637bb-f3a6-47bd-8557-afceab72f160      
  notification-url:  https://slug-scrooge-enquirer.ngrok-free.dev/payments/webhook

gemini:
  api:
    key: 
