spring:
  application:
    name: TurboMechanics
  
  datasource: 
    url: jdbc:postgresql://localhost:5432/Turbo_Mechanics
    username: postgres
    password: santi0103
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: juanjosemunozgarcia745@gmail.com     # Cambiar por el correo del taller
    password: eqku buvf ypdq ugtq            # Contraseña de aplicación de Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090

security:
  jwt:
    secret-key: QjaJfdfFv7krX863yrVAS87tfaz56rUWcrUzS0ZbqFU= # Genera con openssl rand -base64 32
    token-expiration: 600000 # 10 min expresado en ms

whatsapp:
  service:
    url: http://localhost:3001
    token: turbo_mechanics_2026
  session:
    default: admin
    
app:
  frontend:
    url: http://localhost:4200

gemini:
  api:
    key: